# Generated by Django 5.2.12 on 2026-08-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('liked_by', 'liked_post'), name='unique_like'),
        ),
    ]
